
const RR_USERS='rr_users_v3', RR_SESSION='rr_session_v3', RR_TRIPS='rr_trips_v3', RR_OWNER='rr_owner_ok_v1';
const $=id=>document.getElementById(id); const money=n=>'$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2});
function toast(m){let t=$('toast'); if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)} t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function read(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function users(){return read(RR_USERS,{})} function session(){return read(RR_SESSION,null)}
function requireLogin(){if(!session()) location.href='login.html?next=dashboard.html'}
function logout(){localStorage.removeItem(RR_SESSION); location.href='index.html'}
function trips(){return read(RR_TRIPS,[])} function saveTrips(v){write(RR_TRIPS,v)}
function myTrips(){let s=session(); return trips().filter(t=>s&&t.email===s.email)}
function signup(e){e.preventDefault(); let name=$('name').value.trim(), email=$('email').value.trim().toLowerCase(), pass=$('password').value, pass2=$('password2').value; if(!name||!email||!pass)return toast('Fill out all fields'); if(pass!==pass2)return toast('Passwords do not match'); let u=users(); if(u[email])return toast('Account already exists — log in'); u[email]={name,email,pass,createdAt:new Date().toISOString()}; write(RR_USERS,u); write(RR_SESSION,{name,email}); location.href='dashboard.html'}
function login(e){e.preventDefault(); let email=$('email').value.trim().toLowerCase(), pass=$('password').value; let u=users(); if(!u[email]||u[email].pass!==pass)return toast('Email or password not found'); write(RR_SESSION,{name:u[email].name,email}); let next=new URLSearchParams(location.search).get('next')||'dashboard.html'; location.href=next}
function addTrip(e){e.preventDefault(); let s=session(); if(!s)return requireLogin(); let row={id:Date.now(),email:s.email,name:s.name,flightNo:$('flightNo').value.trim(),confirmationNo:$('confirmationNo').value.trim().toUpperCase(),route:$('route').value.trim(),travelDate:$('travelDate').value,paid:Number($('paid').value),bookingSource:$('bookingSource').value.trim(),notes:$('notes').value.trim(),status:'Monitoring',createdAt:new Date().toISOString(),currentPrice:null,drop:0,customerApproved:false,ownerNote:''}; saveTrips([row,...trips()]); e.target.reset(); toast('Flight saved'); renderTrips()}
function renderTrips(){let box=$('trips'); if(!box)return; let rows=myTrips(); box.innerHTML=rows.length?rows.map(r=>`<div class="trip"><div class="row"><div><h3>${r.flightNo} • ${r.route}</h3><p>${r.travelDate||''} • Paid ${money(r.paid)} • ${r.bookingSource||'Booking source not listed'}${r.confirmationNo?` • Conf. ${r.confirmationNo}`:''}</p></div><span class="tag">${r.status}</span></div>${r.drop?`<p><b>Potential savings:</b> ${money(r.drop)} • New price ${money(r.currentPrice)}</p>`:'<p>No price drop found yet. RouteRefund is watching this trip.</p>'}${r.notes?`<p><b>Your note:</b> ${r.notes}</p>`:''}${r.ownerNote?`<p><b>RouteRefund note:</b> ${r.ownerNote}</p>`:''}<div class="actions"><button class="btn ghost" data-action="note" data-id="${r.id}">Add note</button>${r.drop?`<button class="btn primary" data-action="approve" data-id="${r.id}">Approve next steps</button>`:''}<button class="btn danger" data-action="remove" data-id="${r.id}">Remove</button></div></div>`).join(''):`<div class="empty"><h3>No trips yet</h3><p>Add your first booked flight above.</p></div>`}
function modal(html){let m=$('modal'); if(!m){m=document.createElement('div');m.id='modal';m.className='modal';m.innerHTML='<div id="modalCard" class="modalCard"></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target.id==='modal')m.classList.remove('open')})} $('modalCard').innerHTML=html; m.classList.add('open')}
function updateTrip(id,fn){saveTrips(trips().map(t=>String(t.id)===String(id)?fn(t):t)); renderTrips(); renderOwner();}
document.addEventListener('click',e=>{let b=e.target.closest('button,[data-action]'); if(!b)return; let a=b.dataset.action,id=b.dataset.id; if(a==='logout')logout(); if(a==='note')modal(`<h2>Add note</h2><div class="field"><textarea id="noteText" placeholder="Example: I prefer credit if cash refund is not possible."></textarea></div><button class="btn primary" data-action="save-note" data-id="${id}">Save note</button>`); if(a==='save-note'){updateTrip(id,t=>({...t,notes:($('noteText').value||t.notes)})); $('modal').classList.remove('open'); toast('Note saved')} if(a==='approve'){updateTrip(id,t=>({...t,customerApproved:true,status:'Customer approved next steps'})); toast('Approved')} if(a==='remove'){saveTrips(trips().filter(t=>String(t.id)!==String(id))); renderTrips(); toast('Removed')} if(a==='owner-login'){let code=($('ownerCode').value||'').trim(); if(code==='route2026'){write(RR_OWNER,true); location.href='owner.html'}else toast('Wrong owner code')} if(a==='owner-logout'){localStorage.removeItem(RR_OWNER); location.href='owner-login.html'} if(a==='scan'){updateTrip(id,t=>{let drop=Math.max(21,Math.round(Number(t.paid||200)*.12));return {...t,currentPrice:Number(t.paid)-drop,drop,status:'Savings found'}}); toast('Sample scan complete')} if(a==='mark-contacted'){updateTrip(id,t=>({...t,status:'Customer contacted'})); toast('Marked contacted')} if(a==='owner-note')modal(`<h2>Owner note</h2><div class="field"><textarea id="ownerNoteText" placeholder="Internal/customer note"></textarea></div><button class="btn primary" data-action="save-owner-note" data-id="${id}">Save note</button>`); if(a==='save-owner-note'){updateTrip(id,t=>({...t,ownerNote:$('ownerNoteText').value,status:'Owner reviewed'})); $('modal').classList.remove('open'); toast('Owner note saved')}});
function renderOwner(){let box=$('ownerTrips'); if(!box)return; let rows=trips(); let k=$('kpis'); if(k){k.innerHTML=`<div class="card"><h2>${rows.length}</h2><p>Total trips</p></div><div class="card"><h2>${rows.filter(r=>r.drop).length}</h2><p>Savings found</p></div><div class="card"><h2>${rows.filter(r=>r.customerApproved).length}</h2><p>Approved</p></div><div class="card"><h2>${money(rows.reduce((a,r)=>a+(r.drop||0),0))}</h2><p>Potential savings</p></div>`} box.innerHTML=rows.length?rows.map(r=>`<div class="trip"><div class="row"><div><h3>${r.flightNo} • ${r.route}</h3><p>${r.name||''} • ${r.email} • ${r.travelDate||''} • Paid ${money(r.paid)}${r.confirmationNo?` • Conf. ${r.confirmationNo}`:''}</p></div><span class="tag">${r.status}</span></div><p>${r.notes||'No customer note'}</p>${r.drop?`<p><b>Found:</b> ${money(r.drop)} drop to ${money(r.currentPrice)}</p>`:''}<div class="actions"><button class="btn ghost" data-action="scan" data-id="${r.id}">Run sample scan</button><button class="btn ghost" data-action="owner-note" data-id="${r.id}">Add owner note</button><button class="btn primary" data-action="mark-contacted" data-id="${r.id}">Mark contacted</button></div></div>`).join(''):`<div class="empty"><h3>No customer trips yet</h3><p>Trips submitted from dashboard.html will appear here in this browser.</p></div>`}
window.addEventListener('DOMContentLoaded',()=>{if(document.body.dataset.page==='dashboard'){requireLogin(); let s=session(); $('welcome').textContent='Welcome, '+(s?.name||s?.email); renderTrips()} if(document.body.dataset.page==='signup')$('signupForm').addEventListener('submit',signup); if(document.body.dataset.page==='login')$('loginForm').addEventListener('submit',login); let f=$('tripForm'); if(f)f.addEventListener('submit',addTrip); if(document.body.dataset.page==='owner'){if(!read(RR_OWNER,false)) location.href='owner-login.html'; else renderOwner()}});
