const RR = window.ROUTEREFUND_CONFIG || {};
const supabaseClient = window.supabase?.createClient(RR.SUPABASE_URL, RR.SUPABASE_ANON_KEY);
const $ = id => document.getElementById(id);
const money = n => '$' + Number(n || 0).toLocaleString(undefined, { maximumFractionDigits: 2 });
function toast(message){let t=$('toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function getUser(){if(!supabaseClient)return null;const {data}=await supabaseClient.auth.getUser();return data?.user||null}
async function ensureProfile(user){if(!user)return;const m=user.user_metadata||{};if(m.name||m.date_of_birth){await supabaseClient.from('profiles').upsert({user_id:user.id,full_name:m.name||'',date_of_birth:m.date_of_birth||null},{onConflict:'user_id'})}}
async function requireLogin(next='trips.html'){const user=await getUser();if(!user){location.href=`login.html?next=${encodeURIComponent(next)}`;return null}await ensureProfile(user);return user}
async function logout(){await supabaseClient.auth.signOut();location.href='index.html'}
async function signup(e){e.preventDefault();const name=$('name').value.trim(),date_of_birth=$('signupDob').value,email=$('email').value.trim().toLowerCase(),password=$('password').value,password2=$('password2').value;if(!name||!date_of_birth||!email||!password)return toast('Fill out all fields');if(password.length<8)return toast('Use at least 8 characters');if(password!==password2)return toast('Passwords do not match');const {data,error}=await supabaseClient.auth.signUp({email,password,options:{data:{name,date_of_birth},emailRedirectTo:`${location.origin}/trips.html`}});if(error)return toast(error.message);if(data?.user)await ensureProfile(data.user);if(data?.session){toast('Account created');location.href='trips.html'}else{toast('Account created. If email confirmation is on, confirm email before logging in.');setTimeout(()=>location.href='login.html',900)}}
async function login(e){e.preventDefault();const email=$('email').value.trim().toLowerCase(),password=$('password').value;const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)return toast(error.message);if(data?.user)await ensureProfile(data.user);const next=new URLSearchParams(location.search).get('next')||($('ownerMode')?'owner.html':'trips.html');location.href=next}
async function forgotEmail(e){e.preventDefault();const payload={full_name:$('recoveryName').value.trim(),date_of_birth:$('recoveryDob').value,status:'New'};if(!payload.full_name||!payload.date_of_birth)return toast('Fill out all required fields');const {error}=await supabaseClient.from('account_recovery_requests').insert(payload);if(error)return toast('Recovery request could not be saved. Run the latest Supabase SQL.');e.target.reset();toast('If we find a match, recovery instructions will be sent to the account email.')}
async function resetPassword(e){e.preventDefault();const email=$('email').value.trim().toLowerCase();const redirectTo=`${location.origin}/update-password.html`;const {error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo});if(error)return toast(error.message);toast('Reset email sent')}
async function updatePassword(e){e.preventDefault();const password=$('password').value,password2=$('password2').value;if(password.length<8)return toast('Use at least 8 characters');if(password!==password2)return toast('Passwords do not match');const {error}=await supabaseClient.auth.updateUser({password});if(error)return toast(error.message);toast('Password updated');setTimeout(()=>location.href='trips.html',600)}
async function addTrip(e){e.preventDefault();const user=await requireLogin('trips.html');if(!user)return;if(!$('changeConsent').checked)return toast('Please accept trip authorization to continue');const airline=$('airlineSelect')?.value?.trim()||'';const rawNotes=$('notes').value.trim();const notes=[airline?`Airline: ${airline}`:'',rawNotes].filter(Boolean).join('\n');const trip={user_id:user.id,passenger_first:$('passengerFirst').value.trim(),passenger_last:$('passengerLast').value.trim(),date_of_birth:$('dateOfBirth').value,confirmation_no:$('confirmationNo').value.trim().toUpperCase(),paid:Number($('paid').value),notes,change_consent:true,status:'Monitoring'};const {error}=await supabaseClient.from('trips').insert(trip);if(error)return toast(error.message);e.target.reset();toast('Flight saved');await renderTrips()}
async function loadTrips(){const {data,error}=await supabaseClient.from('trips').select('*').order('created_at',{ascending:false});if(error){toast(error.message);return[]}return data||[]}
async function renderTrips(){const box=$('trips');if(!box)return;const rows=await loadTrips();box.innerHTML=rows.length?rows.map(r=>`<div class="trip"><div class="row"><div><h3>Confirmation ${escapeHtml(r.confirmation_no||'')}</h3><p>Paid ${money(r.paid)} • Passenger: ${escapeHtml(r.passenger_first||'')} ${escapeHtml(r.passenger_last||'')}</p></div><span class="tag">${escapeHtml(r.status||'Monitoring')}</span></div>${r.current_price?`<p><b>Potential savings:</b> ${money(Number(r.paid)-Number(r.current_price))} • New price ${money(r.current_price)}</p>`:'<p>No price drop found yet. RouteRefund is watching this trip.</p>'}${r.notes?`<p><b>Your note:</b> ${escapeHtml(r.notes)}</p>`:''}<div class="actions"><button class="btn ghost" data-action="note" data-id="${r.id}">Add note</button><button class="btn danger" data-action="remove" data-id="${r.id}">Remove</button></div></div>`).join(''):`<div class="empty"><h3>No trips yet</h3><p>Add your first booked flight above.</p></div>`}
function modal(html){if(!$('modal'))return;$('modalCard').innerHTML=html;$('modal').classList.add('open')}
async function updateTrip(id,patch,owner=false){const {error}=await supabaseClient.from('trips').update(patch).eq('id',id);if(error)return toast(error.message);owner?await renderOwner():await renderTrips()}
async function removeTrip(id){const {error}=await supabaseClient.from('trips').delete().eq('id',id);if(error)return toast(error.message);toast('Removed');await renderTrips()}
async function renderOwner(){const box=$('ownerTrips');if(!box)return;const {data:rows,error}=await supabaseClient.from('trips').select('*').order('created_at',{ascending:false});if(error){box.innerHTML=`<div class="panel"><h2>Access blocked</h2><p>${escapeHtml(error.message)}</p><p>Run the Supabase security SQL and add your owner email before using this dashboard.</p></div>`;return}const total=rows?.length||0,monitoring=rows?.filter(r=>r.status==='Monitoring').length||0,found=rows?.filter(r=>r.status==='Savings found').length||0;if($('kpis'))$('kpis').innerHTML=`<div><b>${total}</b><span>Total trips</span></div><div><b>${monitoring}</b><span>Monitoring</span></div><div><b>${found}</b><span>Savings found</span></div>`;box.innerHTML=total?rows.map(r=>`<div class="trip"><div class="row"><div><h3>Confirmation ${escapeHtml(r.confirmation_no||'')}</h3><p>Paid ${money(r.paid)} • Passenger: ${escapeHtml(r.passenger_first||'')} ${escapeHtml(r.passenger_last||'')} • DOB: ${escapeHtml(r.date_of_birth||'')}</p><p>User ID: ${escapeHtml(r.user_id||'')}</p>${r.notes?`<p><b>Note:</b> ${escapeHtml(r.notes)}</p>`:''}</div><span class="tag">${escapeHtml(r.status||'')}</span></div><div class="actions"><button class="btn ghost" data-action="owner-price" data-id="${r.id}">Add price found</button><button class="btn ghost" data-action="owner-status" data-id="${r.id}" data-status="Monitoring">Monitoring</button><button class="btn primary" data-action="owner-status" data-id="${r.id}" data-status="Savings found">Savings found</button><button class="btn danger" data-action="owner-status" data-id="${r.id}" data-status="Closed">Close</button></div></div>`).join(''):`<div class="empty"><h3>No customer trips yet</h3></div>`}
document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-action]');if(!b)return;const action=b.dataset.action,id=b.dataset.id;if(action==='mobile-menu')return modal('<h2>Menu</h2><div class="mobileMenuList"><a href="how-it-works.html">How it works</a><a href="supported-airlines.html">Airlines</a><a href="trust-center.html">Trust center</a><a href="faq.html">FAQ</a><a href="forward-confirmation.html">Forward confirmation</a><a href="login.html">Log in</a><a href="signup.html">Create account</a><a href="add-trip.html">Start tracking</a></div>');if(action==='logout')return logout();if(action==='remove')return removeTrip(id);if(action==='note')return modal(`<h2>Add note</h2><label>Note<textarea id="noteText" placeholder="Example: I prefer credit if cash refund is not possible."></textarea></label><button class="btn primary" data-action="save-note" data-id="${id}">Save note</button>`);if(action==='save-note'){await updateTrip(id,{notes:$('noteText').value.trim()});$('modal').classList.remove('open');return toast('Note saved')}if(action==='owner-status')return updateTrip(id,{status:b.dataset.status},true);if(action==='owner-price')return modal(`<h2>Add found price</h2><label>Current lower price<input id="foundPrice" type="number" step="0.01"></label><button class="btn primary" data-action="save-owner-price" data-id="${id}">Save price</button>`);if(action==='save-owner-price'){await updateTrip(id,{current_price:Number($('foundPrice').value),status:'Savings found'},true);$('modal').classList.remove('open');return toast('Price saved')}});
function syncPublicNav(){const publicPages=new Set(['home','info']);const page=document.body.dataset.page;if(!publicPages.has(page))return;const links=document.querySelector('.nav .links');if(!links)return;links.innerHTML='<a class="hide-sm" href="how-it-works.html">How it works</a><a class="hide-sm" href="supported-airlines.html">Airlines</a><a class="hide-sm" href="trust-center.html">Trust</a><a class="hide-sm" href="faq.html">FAQ</a><a class="btn ghost" href="login.html">Log in</a><a class="btn primary" href="add-trip.html">Start tracking</a><button class="btn ghost mobileMenuBtn" data-action="mobile-menu" aria-label="Open menu">Menu</button>'}
window.addEventListener('DOMContentLoaded',async()=>{syncPublicNav();if(!supabaseClient)return toast('Missing Supabase config');if($('modal'))$('modal').addEventListener('click',e=>{if(e.target.id==='modal')$('modal').classList.remove('open')});if(document.body.dataset.page==='signup')$('signupForm').addEventListener('submit',signup);if(document.body.dataset.page==='login')$('loginForm').addEventListener('submit',login);if(document.body.dataset.page==='reset')$('resetForm').addEventListener('submit',resetPassword);if(document.body.dataset.page==='forgot-email')$('forgotEmailForm').addEventListener('submit',forgotEmail);if(document.body.dataset.page==='update-password')$('updatePasswordForm').addEventListener('submit',updatePassword);if(document.body.dataset.page==='dashboard'){const user=await requireLogin('trips.html');if(!user)return;$('welcome').textContent=user.email;$('tripForm').addEventListener('submit',addTrip);await renderTrips()}if(document.body.dataset.page==='owner'){const user=await requireLogin('owner.html');if(!user)return;$('ownerWelcome').textContent=user.email;await renderOwner()}});
